[package]
name = "day_6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fileutils = { path = "../fileutils" }
bounded-vec-deque = "0.1.1"

[dev-dependencies]
test-case = "2.2.2"