[package]
name = "day_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
execute = { path = "../execute" }
[dev-dependencies]
test-case = "3.3.1"
