[package]
name = "day_8"
version = "0.1.0"
edition = "2021"

[dependencies]
fileutils = { path = "../fileutils" }

lazy_static = "1.4.0"
regex = "1.4.3"
num-integer = "0.1.45"
[dev-dependencies]
test-case = "3.3.1"